### ISSUE TITLE
Feedback for "What Is SAP Task Center?"

### ISSUE THREAD

**Issue by GGa65** [SAP-docs/btp-task-center#10]
https://help.sap.com/docs/TASK_CENTER/08cbda59b4954e93abb2ec85f1db399d/9693186f1fe54cbe801085d6bdfe8287.html

Dear colleagues
in my SAP Identity I am Gerald Galka, D033819, gerald.galka@sap.com.
I saw in the SAP ommunity this [blog-post](https://blogs.sap.com/2023/02/01/collaborate-with-us-sap-task-center-opens-its-documentation-for-your-feedback-with-github/?source=email-global-notification-bp-new-in-tag-followed) and I must say, I like it! 
It would be an opportunity to make our customers a valuable part of of our engineering community, right? ;-)
I would like to learn a bit more about the process behind it.
Would it be possible to give me some hints:
I can setup a meeting internally, but please give me first some reaction about my external feedback here to my external identity, to give me a real example as it could look like.
1000 thanks
Gerald

**Comment by valvalkanova** [comment]
Hi Gerald, thanks for contacting us on GitHub! We also see this as a great opportunity to receive customer feedback. I'm sending you an email internally to discuss further details.  
Have a great day ahead! 
Valentina
