### ISSUE TITLE
Feedback for "Identity Directory Connectivity"

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-task-center#14]
https://help.sap.com/docs/TASK_CENTER/08cbda59b4954e93abb2ec85f1db399d/3dcfba91f69942b29bd924f75bf51c10.html

Could you kindly specify which authorizations are needed for the system within Cloud Identity Services? Is "read users" authorization sufficent?
![image](https://user-images.githubusercontent.com/38477763/225757639-70823212-7c28-43d8-9406-4c749919c700.png)

**Comment by mar-hol** [comment]
also you get "client user" and "client secret" (and not user / password) when you create an administrator and generate a secrete in SAP Cloud Identity Service
![image](https://user-images.githubusercontent.com/38477763/225759483-dccc8bc3-b002-4665-b1ba-065d984e4845.png)

**Comment by mar-hol** [comment]
Any update on this?

**Comment by valvalkanova** [comment]
Hi Marco, 
Thank you for your patience and feedback.
I have updated the terms for _user ID_ and _password_ and the correct ones will be visible with the next release.
Regarding your question about the required authorizations - "Read Users" is sufficient, and will be mentioned in the documentation as well.
Best regards, 
Valentina

**Comment by mar-hol** [comment]
> Thank you for your valuable feedback contribution, @mar-hol! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/mar-hol
