### ISSUE TITLE
Feedback for "Conventions and Technical Restrictions"

### ISSUE THREAD

**Issue by BeneetaG** [SAP-docs/btp-task-center#15]
https://help.sap.com/docs/TASK_CENTER/08cbda59b4954e93abb2ec85f1db399d/f0f13bf49e3f45488bcf24218a2771e4.html?locale=en-US

Please update the information regarding Substitution Management (Point no. 2) under 'Technical Restrictions'.  Since this feature is supported for SAP Fieldglass, we need to make the necessary changes.

**Comment by valvalkanova** [comment]
Hi Beneeta,
Thank you for your comment! This information about the restriction is already available in the User guide. 
After a discussion with the PO, we decided to not mention Substitution Management under Technical Restrictions, as it is not a restriction by SAP Task Center, but rather a feature that has to be enabled by the task provider. 
Additionally we'll be working on a new section in the documentation to visualize the supported features by the different task providers.  
Thanks for your feedback and feel free to contact me if you have any questions.
Best regards, 
Valentina

**Comment by BeneetaG** [comment]
https://community.sap.com/t5/user/viewprofilepage/user-id/12260


From: sap-doc-bot[bot] ***@***.***>
Date: Tuesday, 6. February 2024 at 12:31
To: SAP-docs/btp-task-center ***@***.***>
Cc: George, Beneeta ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP-docs/btp-task-center] Feedback for "Conventions and Technical Restrictions" (Issue #15)

Thank you for your valuable feedback contribution, @BeneetaG<https://github.com/BeneetaG>! So that we can recognize your contribution in SAP Community<https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md>, please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:

https://people.sap.com/your-user-name

Thanks!
