### ISSUE TITLE
linked SAP Note not released for customer

### ISSUE THREAD

**Issue by mar-hol** [SAP-docs/btp-task-center#18]
### Issue description

the linked SAP Note 3070097 is currently not released for customers
![image](https://github.com/SAP-docs/btp-task-center/assets/38477763/203c470b-c626-4947-87b8-a5a947de714d)

### Feedback Type (Optional)

None

### Page Title on SAP Help Portal (prefilled)

Supported Features

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/supported-features?version=Cloud

**Comment by LilyanaOviPe** [comment]
Hi @mar-hol, thanks for your contribution. We appreciate it. Indeed, the note you mention was in the process of being updated. So we were advised to reference the SAP Note 2975987 instead. We've just released the new documentation, so you can check out the link again https://help.sap.com/docs/task-center/sap-task-center/supported-features?version=Cloud. 
You can also take a look at our new features Claim, Release, Forward: https://help.sap.com/docs/task-center/sap-task-center/what-s-new-for-sap-task-center?version=Cloud. 
Thanks again for your input. It's really valuable for us.
