### ISSUE TITLE
Principal propagation as a feature in the Supported Features table

### ISSUE THREAD

**Issue by ssimsekler** [SAP-docs/btp-task-center#19]
### Issue description

Hello

I believe it would be good for the users to understand whether principal propagation is supported in case of task approvals for different SAP applications.

Principal propagation is a great value offered by SAP Task Center (wherever applicable) and can make it a preferable option, e.g., against a custom app.

Kind Regards

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Supported Features

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/supported-features?locale=en-US

**Comment by LilyanaOviPe** [comment]
Hi, @ssimsekler, thank you for your suggestion. We really appreciate it. Once SAP Task Center supports 3rd party task provider integration, there will be additional documentation provided to help implementation and integration efforts including coverage for principal propagation flows.
