### ISSUE TITLE
Dedicated page for principal propagation in SAP Help site for SAP Task Center.

### ISSUE THREAD

**Issue by ssimsekler** [SAP-docs/btp-task-center#20]
### Issue description

Hello

Principal propagation is a great value offered by SAP Task Center (wherever applicable) and can make it a preferable option for consolidating and managing tasks across several applications. It can be a distinguishing feature against other options like creating a custom app.

Therefore, I believe a dedicated page explaining principal propagation, and how SAP Task Center provides and handles it, would be a great addition to the SAP Help site for SAP Task Center.

Kind Regards

Serdar

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Security

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/security?locale=en-US

**Comment by LilyanaOviPe** [comment]
Hi, @ssimsekler, thanks for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by LilyanaOviPe** [comment]
Hi Serdar, thank you very much for your suggestion. Once SAP Task Center supports 3rd party task provider integration, there would be additional documentation provided to help implementation and integration efforts including coverage for principal propagation flows.
