### ISSUE TITLE
Bad link:  Set Up Principal Propagation Between Subaccounts

### ISSUE THREAD

**Issue by mikeedoyle** [SAP-docs/btp-task-center#21]
### Issue description

The hyperlink '[Set Up Principal Propagation Between Subaccounts](https://help.sap.com/docs/PROCESS_AUTOMATION/a331c4ef0a9d48a89c779fd449c022e7/644357977e414211a730dab2e3094585.html)' doesn't have the correct ref.  I believe it should be https://help.sap.com/docs/build-process-automation/sap-build-process-automation/set-up-principal-propagation-between-subaccounts-87df988656ad4190900c209b1d1780b0

### Feedback Type (Optional)

linking

### Page Title on SAP Help Portal (prefilled)

Work with SAP Build Process Automation Tasks from a Remote Subaccount

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/work-with-sap-build-process-automation-tasks-from-remote-subaccount

**Comment by valvalkanova** [comment]
Thank you very much for your feedback. We'll update the link.

**Comment by mikeedoyle** [comment]
13892
