### ISSUE TITLE
Description of Role TaskCenterBusinessAdministrator is missing

### ISSUE THREAD

**Issue by sebastianesch** [SAP-docs/btp-task-center#23]
### Issue description

The Role TaskCenterBusinessAdministrator is not described.

### Feedback Type (Optional)

content gaps

### Page Title on SAP Help Portal (prefilled)

Authorization Configuration

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/authorization-configuration

**Comment by LilyanaOviPe** [comment]
Hi,  @sebastianesch. Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by sebastianesch** [comment]
> Thank you for your valuable feedback contribution, @sebastianesch! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

My User ID is 3335

**Comment by LilyanaOviPe** [comment]
Hi, @sebastianesch. Thank you for your feedback, it's really important to us. I've forwarded your comments to the responsible people. 

Best regards,
Lilyana
