### ISSUE TITLE
Can't get it to work with the instructions - should this not be a connection based on a technical user?

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-task-center#27]
### Issue description

- No 'SystemUser' property in the destination + type OAuthSAMLBearer = JWT context required

Since it's SAP Task Center's backend that will use the destination to fetch tasks from Work Zone, I don't see how this can work or is there a certain hard-coded "user_uuid" provided by SAP Task Center and SAP Work Zone?

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Connect SAP Build Work Zone, advanced edition and SAP Task Center

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/connect-sap-build-work-zone-advanced-edition-and-sap-task-center?locale=en-US

**Comment by LilyanaOviPe** [comment]
Hi, @piejanssens. Thank you for your feedback. We’ll look into it and come back to you if we have any questions.

**Comment by valvalkanova** [comment]
Hi Pieter, 
To get tasks from SAP Build Work Zone, advanced edition, SAP Task Center uses client credentials authentication. The flow is configured using the described destination properties. 
If you have followed the official documentation and you still have issues receiving tasks, please open a ticket to the component of SAP Task Center or the respective task provider. You can find the list of components here: https://me.sap.com/notes/3044195 
Best regards, 
Valentina

**Comment by piejanssens** [comment]
If it was client credentials, then it would be a destination of the type "OAuth Client Credentials" and not "OAuth2SAMLBearerAssertion". That is not the case. 

Can we reopen this?

P.S.: our case `1022723/2024` (current status - we are asked to provide browser traces 🤦 )
