### ISSUE TITLE
Why is a new service instance required instead of a new service key for one and the same SAP Task Center service instance?

### ISSUE THREAD

**Issue by piejanssens** [SAP-docs/btp-task-center#28]
### Issue description

Is there a technical constraint or should the documentation state that a new service key should be created for the SAP Task Center instance?

The same is mentioned in the SAP Fieldglass documentation: https://help.sap.com/docs/TASK_CENTER/sap-task-center/connect-sap-fieldglass-and-sap-task-center?locale=en-US&state=PRODUCTION&version=Cloud&q=%22Create%20a%20new%20service%20instance%22

### Feedback Type (Optional)

clarity

### Page Title on SAP Help Portal (prefilled)

Creating the Primary Destination with the Technical User

### Page URL on SAP Help Portal (prefilled)

https://help.sap.com/docs/task-center/sap-task-center/creating-primary-destination-with-technical-user-sfsf?locale=en-US

**Comment by valvalkanova** [comment]
Hi Pieter, 
For each task provider supporting PUSH of task updates, SAP Task Center needs a separate service instance. Service keys of different service instances have different client IDs, which SAP Task Center uses to distinguish between the task providers. 
I hope this helps.
Best regards, 
Valentina

**Comment by piejanssens** [comment]
This seems to be very important information that belongs on this page: https://help.sap.com/docs/task-center/sap-task-center/destinations-to-task-providers?locale=en-US

It would be more logical that for this requirement there would be a separate Task Center service plan for push providers, next to the principal service itself.
